#!/bin/bash
#
# NOX       Startup script for the NOX controller
#
# chkconfig: 2345 81 30
# description: Stars aopenflow controller 
# processname: nox_core

#THIS FILE REQUIRES EDITING FOR CORRECT OPERATION

# Source function library
if [ -f /etc/rc.d/init.d/functions ]; then
. /etc/rc.d/init.d/functions
elif [ -f /etc/init.d/functions ]; then
. /etc/init.d/functions
elif [ -f /etc/rc.d/functions ]; then
. /etc/rc.d/functions
fi

[ -e /etc/sysconfig/nox_cored ] && . /etc/sysconfig/nox_cored

#if NOX_CONTROLLER_PORT not set by /etc/sysconfig/nox_cored, default is 6633
: ${NOX_CONTROLLER_PORT:=6633}
: ${NOX_CONTROLLER_IP:=0.0.0.0}

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0
name=nox
#base_dir=/CHANGEME/
controller=/usr/bin/nox_core

vlan=$(/usr/bin/xml_grep --text_only '/config/discovery_vlan' /etc/oess/database.xml)
if [ -n "$vlan" ];
then
    if [ "$vlan" -ne "-1" ];
    then
	    options=" -d -i ptcp:$NOX_CONTROLLER_IP:$NOX_CONTROLLER_PORT discovery=15,$vlan nddi_dbus -n /var/log/nox/nox.info"
    else
	    options=" -d -i ptcp:$NOX_CONTROLLER_IP:$NOX_CONTROLLER_PORT nddi_dbus -n /var/log/nox/nox.info"
    fi
else
    options=" -d -i ptcp:$NOX_CONTROLLER_IP:$NOX_CONTROLLER_PORT nddi_dbus -n /var/log/nox/nox.info"
fi

username=_oess
lockfile=/var/lock/subsys/$name
command="$controller   $options"
PIDFILE=/var/run/nox/nox.pid
command="$controller  -p $PIDFILE $options"
#echo $command


#set -x

# See how we were called.
case "$1" in
  start)
        #start
        echo -n $"Starting $name Controller: "
#so nox is retarted and writes it PID file even when it fails to start,
#so we need to write a workaround here
        IS_RUNNING=0
	if [ -f $PIDFILE ]; then
		MYPID=`head -n 1 $PIDFILE`
		TEST_RUNNING=`ps -p ${MYPID} | grep ${MYPID}`
                if [ -z "${TEST_RUNNING}" ];
                then
                    IS_RUNNING=0
                else
                    IS_RUNNING=1
                fi
        fi

        if [ $IS_RUNNING != 0 ];then
            failure; echo
        else
	    cd /usr/bin
            sudo -u $username $command

            if [ $? -eq 0 ]; then
                touch $lockfile
                success; echo
            else
                failure; echo
            fi
        fi
        ;;
  stop)
        #stop
        if [ -f $PIDFILE ]; then
                action $"Stopping ${name}: " /bin/true
                kill -TERM `cat $PIDFILE`
                rm -f $PIDFILE
        else
                action $"Stopping ${name}: " /bin/false
        fi
        rm -rf $lockfile
        ;;
  status)
        #snapp -p $base_dir/db/PID $command
        #RETVAL=$?
        #status p0f
	if [ -f $PIDFILE ]; then
		MYPID=`head -n 1 $PIDFILE`
		TEST_RUNNING=`ps -p ${MYPID} | grep ${MYPID}`
		if [ -z "${TEST_RUNNING}" ]
		then
			echo "$name (pid `cat $PIDFILE`) is not running (but PID file exists)"
			exit 3
		else
			echo "$name (pid `cat $PIDFILE`) is running"
		fi
	else
		echo "oess-$name is not running"
		exit 3
	fi
	exit $?
	;;


  restart)
        $0 stop
        #wee need to sleep to make sure the deamon has enoth time to shutdown
        sleep 3
        $0 start
        exit $?
        ;;
  reload)
        reload
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status|help}"
        exit 1

esac

exit $RETVAL

