#!/bin/bash
#
# Startup script for all OE-SS parts (fwdctl, topo, vlan_stats, syslogger)
#
# chkconfig: 2345 81 30
# description: Starts all OE-SS daemons in the proper order


# Source function library
if [ -f /etc/rc.d/init.d/functions ]; then
. /etc/rc.d/init.d/functions
elif [ -f /etc/init.d/functions ]; then
. /etc/init.d/functions
elif [ -f /etc/rc.d/functions ]; then
. /etc/rc.d/functions
fi

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0


#see how we were called.
case "$1" in
  start)
        #start
	/etc/init.d/oess-topo start && /etc/init.d/oess-vlan_stats start && /etc/init.d/nox_cored start && /etc/init.d/oess-fwdctl start && /etc/init.d/oess-notification start && /etc/init.d/oess-fvd start && /etc/init.d/oess-watchdog start
        ;;
  stop)
        #stop
	/etc/init.d/oess-topo stop && /etc/init.d/oess-vlan_stats stop && /etc/init.d/nox_cored stop &&	/etc/init.d/oess-fwdctl stop &&	/etc/init.d/oess-notification stop && /etc/init.d/oess-fvd stop && /etc/init.d/oess-watchdog stop
        ;;
  status)
        #status p0f
	/etc/init.d/oess-topo status
	/etc/init.d/oess-vlan_stats status
	/etc/init.d/nox_cored status
	/etc/init.d/oess-fwdctl status
	/etc/init.d/oess-notification status
	/etc/init.d/oess-fvd status
        /etc/init.d/oess-watchdog status
        ;;

  restart)
        $0 stop
        #wee need to sleep to make sure the deamon has enoth time to shutdown
        sleep 3
        $0 start
        exit $?
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart||status|help}"
        exit 1

esac

exit $RETVAL

