#!/bin/sh
# chkconfig: 123456 90 10
#

options=" /usr/lib/python2.6/site-packages/oess/nddi_dbus.py /usr/lib/python2.6/site-packages/ryu/topology/switches.py --ofp-tcp-listen-port=6636 --lldp-vlan-id=2001 --observe-links --use-syslog --nouse-stderr"

CMD="ryu-manager $options"
 
start() {
    $CMD 2>&1 &
    echo "Ryu Started"
}
 
stop() {
    pid=`ps -ef | grep 'ryu-manager' | grep -v "grep" | awk '{ print $2 }'`
    echo $pid
    kill $pid
    sleep 2
    echo "Ryu Stopped"
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop   
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/scipass {start|stop|restart}"
    exit 1
esac
exit 0