#!/bin/bash
#
# Startup script for the OESS Traceroute Daemon
#
# chkconfig: 2345 81 30
# description: OE-SS Traceroute Daemon - it listens for requests to trace the path of a circuit and injects rules and flow rules to mimic traceroute functionality.
# processname: /usr/bin/oess-traceroute.pl

#THIS FILE REQUIRES EDITING FOR CORRECT OPERATION
#EDIT the variables name and basedir!
#ALSO EDIT the filename before copying to /etc/init.d

# Source function library
if [ -f /etc/rc.d/init.d/functions ]; then
. /etc/rc.d/init.d/functions
elif [ -f /etc/init.d/functions ]; then
. /etc/init.d/functions
elif [ -f /etc/rc.d/functions ]; then
. /etc/rc.d/functions
fi

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0
name=traceroute
exec_file=/usr/bin/oess-$name.pl
options="-d"
username=_oess
lockfile=/var/lock/subsys/$name
command="$exec_file -u $username $options"
PIDFILE=/var/run/oess/oess-$name.pid

#see how we were called.
case "$1" in
  start)
        #start
        IS_RUNNING=0
        echo -n $"Starting $name: "
        if [[ -f $lockfile  && -f $PIDFILE ]];then
            MYPID=`head -n 1 $PIDFILE`
            TEST_RUNNING=`ps -p ${MYPID} | grep ${MYPID}`
            if [ -z "${TEST_RUNNING}" ];
            then
               IS_RUNNING=0
            else
               IS_RUNNING=1
            fi
           
        fi
        if [ $IS_RUNNING != 0 ];then
            failure; echo
            exit 1;
        else
            $command -d

            if [ $? -eq 0 ]; then
                touch $lockfile
                success; echo
            else
                failure; echo
                exit 1;
            fi
        fi
        ;;
  start-instrument)
        #start
        IS_RUNNING=0
        echo -n $"Starting $name: "
        if [[ -f $lockfile  && -f $PIDFILE ]];then
            MYPID=`head -n 1 $PIDFILE`
            TEST_RUNNING=`ps -p ${MYPID} | grep ${MYPID}`
            if [ -z "${TEST_RUNNING}" ];
            then
               IS_RUNNING=0
            else
               IS_RUNNING=1
            fi

        fi
        if [ $IS_RUNNING != 0 ];then
            failure; echo
        else
            if [ -e /tmp/fvd_cover/ ]; then
                rm -rf /tmp/fvd_cover/
            fi
            mkdir -p /tmp/fvd_cover/cover_db
            chmod 777 /tmp/fvd_cover -R
            /usr/bin/perl -MDevel::Cover=-dir,/tmp/fvd_cover/,+select,OESS $command &

            if [ $? -eq 0 ]; then
                echo $! > /var/run/oess/fvd.pid
                touch $lockfile
                success; echo
            else
                failure; echo
            fi
        fi
        ;;
  stop)
        #stop
        if [ -f $PIDFILE ]; then
                action $"Stopping ${name}: " /bin/true
                kill -TERM `cat $PIDFILE`
                rm -f $PIDFILE
        else
                action $"Stopping ${name}: " /bin/false
                exit 1;
        fi
        rm -rf $lockfile
        ;;

  stop-instrument)
        #stop
        if [ -f $PIDFILE ]; then
                action $"Stopping oess-${name}: " /bin/true
                kill -HUP `cat $PIDFILE`
                rm -f $PIDFILE
        else
                action $"Stopping oess-${name}: " /bin/false
        fi
        rm -rf $lockfile
        ;;

  status)
        #status p0f
        if [ -f $PIDFILE ]; then
                MYPID=`head -n 1 $PIDFILE`
                TEST_RUNNING=`ps -p ${MYPID} | grep ${MYPID}`
                if [ -z "${TEST_RUNNING}" ];
                then
                    echo "$name (pid `cat $PIDFILE`) is not running (but PID file exists)"
		    exit 3
                else
                    echo "$name (pid `cat $PIDFILE`) is running"
                fi
        else
                echo "$name is not running"
		exit 3
        fi
        exit $?
        ;;

  restart)
        $0 stop
        #wee need to sleep to make sure the deamon has enoth time to shutdown
        sleep 3
        $0 start
        exit $?
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|start-instrument|stop-instrument|reload|status|help}"
        exit 1

esac

exit $RETVAL

