FROM centos:7

COPY globalnoc-public-el7.repo /etc/yum.repos.d/globalnoc-public-el7.repo
RUN curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
RUN curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

RUN yum makecache
RUN yum -y install epel-release
RUN yum -y install perl httpd mariadb-server rabbitmq-server
RUN yum -y install perl-Carp-Always perl-Test-Deep perl-Test-Exception perl-Test-Pod perl-Test-Pod-Coverage perl-Devel-Cover perl-Net-AMQP-RabbitMQ perl-LWP-Protocol-https perl-AnyEvent-HTTP perl-GRNOC-CLI perl-Text-CSV perl-Net-IP
RUN yum -y install perl-OESS oess-core oess-frontend yui2

COPY app/mpls/mpls_discovery.pl /usr/bin/mpls_discovery.pl
COPY app/mpls/mpls_fwdctl.pl /usr/bin/mpls_fwdctl.pl
COPY app/oess_pull_aws_interfaces.pl /usr/bin/oess_pull_aws_interfaces.pl
COPY app/oess_pull_azure_interfaces.pl /usr/bin/oess_pull_azure_interfaces.pl
COPY app/oess_pull_gcp_interfaces.pl /usr/bin/oess_pull_gcp_interfaces.pl
COPY app/oess_pull_oracle_interfaces.pl /usr/bin/oess_pull_oracle_interfaces.pl

COPY frontend/conf/oe-ss.conf.example /etc/httpd/conf.d/oe-ss.conf
COPY app/etc/firmware.xml /etc/oess/firmware.xml
COPY perl-lib/OESS/t/conf/database.xml /etc/oess/database.xml
COPY perl-lib/OESS/t/conf/interface-speed-config.xml /etc/oess/interface-speed-config.xml
COPY perl-lib/OESS/t/conf/logging.conf /etc/oess/logging.conf
COPY perl-lib/OESS/t/conf/passwd.xml /etc/oess/.passwd.xml
COPY perl-lib/OESS/t/conf/integration.sql /etc/oess/integration.sql

COPY perl-lib/OESS/entrypoint.dev.sh /entrypoint.sh
RUN chmod 777 /entrypoint.sh

RUN touch /var/log/oess.log
RUN chmod 666 /var/log/oess.log
