#!/bin/bash
#
# SNAPP        Startup script for the OESS topo
#
# chkconfig: 2345 81 30
# description: Stars a snapp collector which gathers SNMP data from devices specified in the config file
# processname: snapp-collector

#THIS FILE REQUIRES EDITING FOR CORRECT OPERATION
#EDIT the variables name and basedir!
#ALSO EDIT the filename before copying to /etc/init.d

# Source function library
if [ -f /etc/rc.d/init.d/functions ]; then
. /etc/rc.d/init.d/functions
elif [ -f /etc/init.d/functions ]; then
. /etc/init.d/functions
elif [ -f /etc/rc.d/functions ]; then
. /etc/rc.d/functions
fi

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0
#echo $command


#set -x
#ee how we were called.
case "$1" in
  start)
        #start
	/etc/init.d/oess-topo start && /etc/init.d/oess-vlan_stats start && /etc/init.d/nox_cored start && /etc/init.d/oess-fwdctl start && /etc/init.d/oess-syslogger start
        ;;
  stop)
        #stop
	/etc/init.d/oess-topo stop && /etc/init.d/oess-vlan_stats stop && /etc/init.d/nox_cored stop &&	/etc/init.d/oess-fwdctl stop &&	/etc/init.d/oess-syslogger stop
        ;;
  status)
        #snapp -p $base_dir/db/PID $command
        #RETVAL=$?
        #status p0f
	/etc/init.d/oess-topo status
	/etc/init.d/oess-vlan_stats status
	/etc/init.d/nox_cored status
	/etc/init.d/oess-fwdctl status
	/etc/init.d/oess-syslogger status
        ;;

  restart)
        $0 stop
        #wee need to sleep to make sure the deamon has enoth time to shutdown
        sleep 3
        $0 start
        exit $?
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status|help}"
        exit 1

esac

exit $RETVAL

