on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**-dev'
      - 'admin-ui-refresh'
      - 'master'

jobs:
  oess_testing:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Copy repo to /github/workspace
        uses: actions/checkout@v2
      - name: Run perl-OESS tests
        uses: GlobalNOC/OESS@master
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: /OESS/cover_db
